//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioMVC16.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EjercicioMVC16ModelContainer : DbContext
    {
        public EjercicioMVC16ModelContainer()
            : base("name=EjercicioMVC16ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flor> Flores { get; set; }
        public virtual DbSet<Especie> Especies { get; set; }
        public virtual DbSet<Agente> Agentes { get; set; }
        public virtual DbSet<Poliniza> Poliniza { get; set; }
    }
}
