//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioMVC16.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poliniza
    {
        public int Id { get; set; }
        public string Reclamo { get; set; }
        public int FlorId { get; set; }
        public int AgenteId { get; set; }
    
        public virtual Flor Flor { get; set; }
        public virtual Agente Agente { get; set; }
    }
}
